edition = "2024"

format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
indent_style = "Block"
max_width = 100
space_after_colon = true
space_before_colon = false
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
